name: Daily base image update

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  base_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base_containers:
          - "base-go1.19"
          - "base-rustup"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:${{ matrix.base_containers }}"
          push: false
          file: "Dockerfile"
          tags: |
            ${{ matrix.base_containers }}:${{ github.sha }}
            ${{ matrix.base_containers }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            git_version=latest
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}
