name: Build images

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23.1
      - name: Set notification matrix
        id: matrix
        run: |
          echo "::set-output name=matrix::$(.github/bin/find-docker-files.py ${{ steps.changed-files.outputs.all_changed_files }})"

  build:
    environment: main
    needs:
      - setup
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    strategy:
      matrix: "${{ fromJson(needs.setup.outputs.matrix) }}"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Create buildx cache
        run: |
          mkdir -p /tmp/.buildx-cache
      - name: Build and push local
        id: docker_build_local
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:${{ matrix.base }}"
          push: true
          file: "Dockerfile"
          tags: |
            localhost:5000/${{ matrix.base }}:latest
          build-args: |
            git_version=${{ matrix.git_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}
      - name: Extract and push binaries
        run: |
          CONTAINER="$(docker create localhost:5000/${{ matrix.base }}:latest ${{ matrix.base }})"
          BIN_TMP_DIR="/tmp/${{ matrix.base }}"
          mkdir -p "${BIN_TMP_DIR}"
          for FILE_NAME in ${{ matrix.manifest }}; do
            BASE_FILE_NAME="$(basename ${FILE_NAME})"
            docker cp ${CONTAINER}:${FILE_NAME} ${BIN_TMP_DIR}/${BASE_FILE_NAME}
          done
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        id: binary_artifacts
        with:
          name: binary-extracts-${{ matrix.base }}
          path: /tmp/${{ matrix.base }}*
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        id: build_artifacts
        with:
          name: build-cache-${{ matrix.base }}-${{ matrix.git_version }}
          path: /tmp/.buildx-cache

  merged:
    if: github.event.pull_request.merged == true
    needs:
      - setup
    runs-on: ubuntu-latest
    strategy:
      matrix: "${{ fromJson(needs.setup.outputs.matrix) }}"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - name: Download build container cache
        uses: actions/download-artifact@v3
        with:
          name: build_artifacts
      - name: Unzip container cache
        shell: bash
        run: |
          unzip build-cache-${{ matrix.base }}-${{ matrix.git_version }}.zip
          mv build-cache-${{ matrix.base }}-${{ matrix.git_version }} /tmp/.buildx-cache
      - name: Login to DockerHub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push remote
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:${{ matrix.base }}"
          push: true
          file: "Dockerfile"
          tags: |
            cloudnull/${{ matrix.base }}:${{ github.sha }}
            cloudnull/${{ matrix.base }}:${{ matrix.version }}
            cloudnull/${{ matrix.base }}:latest
          build-args: |
            git_version=${{ matrix.git_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: cloudnull/${{ matrix.base }}
          readme-filepath: ${{ matrix.base }}/README.md
      - name: Download binary artifacts
        uses: actions/download-artifact@v3
        with:
          name: binary_artifacts
      - name: Push binaries
        shell: bash
        run: |
          unzip binary-extracts-${{ matrix.base }}.zip
          # PUSH extracted binaries to CDN
